### ISSUE TITLE
4.0 Find_trees output sp object not sf

### ISSUE THREAD

**Issue by liamirwin** [r-lidar/lidR#503]
Hi JR,

Wanted to alert you to the fact that `find_trees` is still outputting sp objects, 

Will be in touch with 4.0 issues as I come across them.

Reprex attached,

Thanks

Liam

``` r
# Issue: Output of find_trees function is SpatialPointsDataframe not sf object

library(lidR)

packageVersion('lidR')
#> [1] '4.0.0'

las <- readLAS(system.file("extdata", "MixedConifer.laz", package="lidR"))

ttops <- find_trees(las, lmf(ws = 2))

class(ttops)
#> [1] "SpatialPointsDataFrame"
#> attr(,"package")
#> [1] "sp"
```

<sup>Created on 2021-11-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by Jean-Romain** [comment]
Yes it does. It is for backward compatibility. I created new functions that return `sf` objects but old functions are planned to be backward compatible to do not breaks user's codes. Please read the [changelog](https://github.com/r-lidar/lidR/blob/devel/NEWS.md) for more details.

If you have some code that uses `find_trees` or other old geospatial stuff please keep going with these old functions. When I asked for beta testers my goal was also to ensure that old codes are not broken. When lidR v4.0.0 will be released however I suggest you to give up with `sp` and fully use `sf` and thus the new functions I created (`locate_tree` in this case)
