### ISSUE TITLE
lidrBook link provides 404 error 

### ISSUE THREAD

**Issue by tgoodbody** [r-lidar/lidR#528]
https://github.com/r-lidar/lidR/blob/847ee4f89befe659a30a89ddba799b991992ca4a/README.md?plain=1#L12

https://r-lidar.github.io/lidRbook/ -- working link

**Comment by Jean-Romain** [comment]
The `master` branch is now v4.0.0 in which I already fixed the link. v4.0.0 will be released as soon as the documentation is reviewed. The book is already up-to-date with v4.0.0 I'll push when released.

Thanks
