### ISSUE TITLE
Cannot run track_sensor on an LAS catalog

### ISSUE THREAD

**Issue by cflynn8** [r-lidar/lidR#553]
Link to the data I am trying to use [here](https://gmuedu-my.sharepoint.com/:f:/g/personal/cflynn8_gmu_edu/Esv5_A6G9ERKhKayJy0V9CsB2Gw5PIE8eHwE5wdN97X6jg?e=NXXevH).

I am unable to use the `track_sensor` function successfully on an `LAScatalog`.  

I can read a single `LAS` file, use `track_sensor` and then `normalize_intensity`. Plotting the `LAS` file before and after the intensity was normalized confirms that everything worked. The `normalize_intensity` function does produce a repeating warning of: 

```
Normalized intensity does not fit in 16 bits. Value clamped to 2^16
```

I read in 9 LAS files (including the singular LAS file mentioned above) as an `LAScatalog` and that worked fine. I run `filter_duplicates` on the `LAScatalog` and it successfully runs with no errors or warnings. However, when I try to run `track_sensor` on the `LAScatalog`, I get the following error:

```
After keeping only first and last returns of multiple return pulses, 38 pulses still have more than 2 points. This dataset is corrupted and gpstime is likely to be invalid. 
```

I get similar results attempting on other `LAS` datasets. Here is my full r code:

```r
library(lidR)
library(future)

las1 <- readLAS("SaltonSeaTestData\\LAS_Copy\\11SPS180600.las", filter = "-drop_withheld")
plot(las1, color = "Intensity")
las1 <- filter_duplicates(las1)
sensor <- track_sensor(las1, Roussel2020(pmin = 50))
las_norm <- normalize_intensity(las1, range_correction(sensor, Rs = 2000))
plot(las_norm, color = "Intensity")


las_cat <- readLAScatalog("\SaltonSeaTestData\\LAS_Copy", filter = "-drop_withheld")
las_cat
las_check(las_cat)

opt_output_files(las_cat) <- "SaltonSeaTestData\\LAS_Copy\\LASNormalized1\\{*}_int_norm"
plan(multisession)

opt_chunk_size(las_cat) <- 500
opt_chunk_buffer(las_cat) <- 20
plot(las_cat, chunk = TRUE)

las_cat <- filter_duplicates(las_cat)

cat_sensor <- track_sensor(las_cat, Roussel2020(interval = 0.5, pmin = 50))
```

**Comment by Jean-Romain** [comment]
Ok I do not have time to test your example right now but the error seems explicit isn't it? 

> After keeping only first and last returns of multiple return pulses, 38 pulses still have more than 2 points. This dataset is corrupted and gpstime is likely to be invalid. 

I cannot see any bug here. Just a useful and explicit error triggered properly. Are you expecting me to investigate why your dataset is incorrectly populated.

**Comment by cflynn8** [comment]
The error is explicit. I apologize for the lack of clarity on my part and not considering the size of the download. 
I did not mean to infer that you should investigate my dataset, although I see that I inadvertently did that. I took the past week to better understand las files and formatting. As the error message indicated, there are returns with the same gps time in my dataset. I used a workflow similar to the one [here ](https://laptrinhx.com/news/completeness-and-correctness-of-discrete-lidar-returns-per-laser-pulse-fired-lp33Rv6/) to classify duplicates as noise and drop them from the las catalog when reading in the data with -drop_class 7. I am now getting a new error that I will open a separate issue for. Thank you for all of your help!
