### ISSUE TITLE
rasterize_canopy missing

### ISSUE THREAD

**Issue by melfed** [r-lidar/lidR#562]
Hi
I just installed the package again and tried using both the help and search function to use rasterize_canopy but its showing the function does not exist.

```r
 chm <- rasterize_canopy(currenttile, res = 20, pitfree(c(0,2,5,10,15), c(0, 1.5)))  
# Error in rasterize_canopy(currenttile, res = 20, pitfree(c(0, 2, 5, 10,  : 
#  could not find function "rasterize_canopy"
```
Any help would be greatly appreciated. 
Thanks!

**Comment by Jean-Romain** [comment]
You either missed to load lidR with `library(lidR)` or you did not installed lidR properly.
