### ISSUE TITLE
error in retile_catalog when using flight lines

### ISSUE THREAD

**Issue by floresteiro** [r-lidar/lidR#563]
Hi,

I am trying to retile flight transects using `catalog_retile`, but the following error arises: 

```r
newctg2 = catalog_retile(ctg2)
#>  |====================================================================| 100%
#>  missing value where TRUE/FALSE needed
#>  Warning message:
#>  An error occured during the automatic merge of 'catalog_apply'. Merging is impossible. A list has been returned.
```

It worked when I used only one flight transect tho. It also worked when I used a dataset of tiles.

Here is the code I used (which is basically the original example from the retile a LAScatalog documentation):

```r
library(lidR)

# catalog with 2 flight lines
ctg = readLAScatalog("Test_2flight_lines")
plot(ctg)

# Create a new set of 500 x 500 m .las files
opt_chunk_buffer(ctg) <- 0
opt_chunk_size(ctg) <- 500                       
opt_filter(ctg) <- ""                              
opt_laz_compression(ctg) <- TRUE
opt_chunk_alignment(ctg) <- c(0,0) 
opt_output_files(ctg) <- paste0(tempdir(), "/retile_{XLEFT}_{YBOTTOM}") 

# preview the chunk pattern
plot(ctg, chunk = TRUE)

newctg = catalog_retile(ctg)
plot(newctg)
```

:link: [link to the data](https://drive.google.com/drive/folders/1QD_6kpDW9LpF1iyNcOq2qqfV6lwSSG4s?usp=sharing)

**Comment by Jean-Romain** [comment]
I tested the following and it works. It means there is something else, maybe something specific with your data. Please share a minimal reproducible example including data if necessary

```r
library(lidR)

# catalog with 2 flight lines
LASfile <- system.file("extdata", "Megaplot.laz", package="lidR")
ctg = readLAScatalog(LASfile)
plot(ctg)

# Create a new set of 500 x 500 m .las files
opt_chunk_buffer(ctg) <- 0
opt_chunk_size(ctg) <- 300                       
opt_filter(ctg) <- ""                              
opt_laz_compression(ctg) <- TRUE
opt_chunk_alignment(ctg) <- c(0,0) 
opt_output_files(ctg) <- paste0(tempdir(), "/retile_{XLEFT}_{YBOTTOM}") 

# preview the chunk pattern
plot(ctg, chunk = TRUE)

newctg = catalog_retile(ctg)
plot(newctg)
```

**Comment by Jean-Romain** [comment]
And please report what `newctg2` contains. It should be a list of strings.

**Comment by floresteiro** [comment]
It worked here, I received that warning message when testing with two flight lines in which the overlap area had some small holes that I hadn't noticed. 

`newctg2 ` contains a list
![image](https://user-images.githubusercontent.com/103131729/162394387-354c401d-e292-43ef-a967-07241fb6504e.png)

So when I tested again using two flight lines that overlap perfectly, I didn't receive that message and the output (`newctg2b`) contained a large LAScatalog:
![image](https://user-images.githubusercontent.com/103131729/162396209-84fcd5bd-eaf7-40ab-a131-1cf35d5875f0.png)

Then I ran the whole dataset. As a result, I still received that same warning message and, similar to `newctg2`, the output contained a list. Despite this warning message, the input was retiled as I wanted, so it does not seem to be a problem. 

Thank you very much for taking your time to check my issue, I really appreciate it!

**Comment by Jean-Romain** [comment]
There is a problem if it does not work as expected. And it doesn't. Could you please share a minimal reproducible example

**Comment by floresteiro** [comment]
Ok, here are the flight lines from my problematic test:
 
https://drive.google.com/drive/folders/1QD_6kpDW9LpF1iyNcOq2qqfV6lwSSG4s?usp=sharing

**Comment by Jean-Romain** [comment]
The link has restricted access

**Comment by floresteiro** [comment]
Sorry, you should be able to access it now

**Comment by Jean-Romain** [comment]
I fixed the bug. It came from the fact that some chunks were empty. Thanks for reporting.

![Rplot](https://user-images.githubusercontent.com/3872279/162501481-1c5d6c98-1b07-4bf2-9857-8a6a07e8f885.jpeg)

By the way your dataset was not spatially indexed so the retiling process took me 15 minutes while with a spatial index it took me 30 seconds. You should always consider indexing your tiles
