### ISSUE TITLE
Error in fast_quantization(las@data[["Z"]], zscale, zoffset)

### ISSUE THREAD

**Issue by cingularities** [r-lidar/lidR#571]
Running normalized height.

```AGL <- normalize_height(canopy_points, DTM, na.rm = TRUE, copy=TRUE)```

Error:
```
Error in fast_quantization(las@data[["Z"]], zscale, zoffset) : 
  Non quantizable value outside the range of representable values of type 'int'
```

I already loaded the file using filter = "-drop_class 7"

lidR version: 4.0.0. [Data](https://drive.google.com/file/d/1Y8apzOpm3PoEM-Tun9r9vI4s1AzotvKi/view?usp=sharing)

**Comment by cingularities** [comment]
[https://drive.google.com/file/d/1Y8apzOpm3PoEM-Tun9r9vI4s1AzotvKi/view?usp=sharing](url)

**Comment by Jean-Romain** [comment]
Can you investigate to reduce the problem to a smaller file/area. Downloading 3 GB will take me hours and I can't load such big file on my computer. And you did non share the DTM. If you computed the DTM with `rasterize_terrain()` please share a minimal reproducible example.

**Comment by cingularities** [comment]
[https://drive.google.com/drive/folders/12Z-vexz_cRNlgkHZLhkv9YIPxNu-_xQ7?usp=sharing](url)
Here you go.
Folder includes canopy points and DTM

**Comment by Jean-Romain** [comment]
Reproduced with 

```r
library(lidR)
library(terra)
setwd("~/Téléchargements/lidR issues/issue 571/")

dtm = rast("DTM_042022.tif")
las = readLAS("canopy_points_042022.las")
nlas <- normalize_height(las, dtm*1)
```

Notice that `na.rm` is no longer useful since v4.0.0 and `copy`,as far as I can remember, never existed. Anyway it does not change anything to the issue.

**Comment by Jean-Romain** [comment]
The Z scale factor is not set to 0 when normalizing. Thanks for reporting.
