### ISSUE TITLE
Tree segmentation for raster stored on disk

### ISSUE THREAD

**Issue by AndresKasekamp** [r-lidar/lidR#597]
I am having an issue segmenting trees in CHM which is read in from disk.
For example:
```r
chm <-rast("path_to_raster.tif")
ttops <- locate_trees(chm , lmf(5))
algo <- dalponte2016(chm , ttops)
crown <- algo()
```
Throws an error:
`Error: Cannot segment the trees from a raster stored on disk. Use segment_trees() or load the raster in memory`

Should 4.0.0 new functionality item number 9 handle this error? If not, how do I read SpatRaster into memory?

**Comment by Jean-Romain** [comment]
I'm glad to see that some people are reading the changelogs :wink: . The changelog is misleading on that point. This is true for point cloud processing i.e. when you are using a `LAScatalog`. When using a `LAScatalog` to process a large coverage the internal engine has tools to deal with large rasters stored on disk. Here you are working with rasters exclusively and no point cloud is involved. `lidR` is a point cloud processing library with only few tool for processing rasters and here you are in the case of pure raster processing and I do not offer any engine for processing large rasters.
