### ISSUE TITLE
merge_spatial only uses attribute value of last row in sf

### ISSUE THREAD

**Issue by jackbuehner** [r-lidar/lidR#600]
I am attempting to merge an elevation attribute from buildings in a shapefile into the points that are within the bounds of the building. However, the value of the merged attribute does not correspond to the correct buildings; it only uses the value from the last building in the shapefile attribute table.

Below is the script I using:
```R
if(!require('lidR')) { install.packages('lidR') }
if(!require('rgdal')) { install.packages('rgdal') }
if(!require('sf')) { install.packages('sf') }

# LAS
lasFilePath = 'gvl_selection.las'
las = lidR::readLAS(lasFilePath)
lasCRS = sf::st_crs(las)

# buildings
buildingsSPDF = rgdal::readOGR(dsn = './', layer = 'gvl_selection_buildings', )
buildings = sf::st_transform(sf::st_as_sf(buildingsSPDF), lasCRS)

# spacial merge
lasWithBuildingMarkers = lidR::merge_spatial(las, buildings, 'TOPELEV') # expect

# expect different building elevations, but it
# uses the building elevation from the last building in the shapefile
print(lasWithBuildingMarkers$TOPELEV)
```

And here is a folder containing the las and shapefile: https://furman-my.sharepoint.com/:f:/g/personal/jbuehner_furman_edu/EohDIqayGWdGvt93eqku_LUBE3q2tiknRwVpHBRGmfBK7w?e=mBypDG

I have also attempted to merge without specifying an attribute name, and instead of applying the id number of each building (there are 14 buildings), it just applies either NA or 14.

**Comment by Jean-Romain** [comment]
Your link points to an empty folder

**Comment by jackbuehner** [comment]
Sorry, the upload didn't finish for some reason. Files should be there now

**Comment by Jean-Romain** [comment]
The output looks good to me

```r
plot(lasWithBuildingMarkers, color = "TOPELEV")
```

![Capture d’écran du 2022-06-21 17-36-08](https://user-images.githubusercontent.com/3872279/174901343-54a72e60-6617-4667-b0e5-a98270088857.png)

**Comment by jackbuehner** [comment]
I'm not sure what was going on, but it is working for me now too. Thank you for your help!
