### ISSUE TITLE
NA's returned from pixel_metrics. 

### ISSUE THREAD

**Issue by joshbauld** [r-lidar/lidR#602]
I'm calculating 90th percentile of point height within 25m^2 pixels, using pixel_metrics, on a las catalog:

```
rh90 <- pixel_metrics(nlas, ~quantile(Z, probs = 0.9), res = 25)
``` 

This is returning a very high number of na's in some sites. This is an example tibble from one raster:

```
[[82]]
# A tibble: 75 x 3
         x       y                                    rh90_site_82
     <dbl>   <dbl>                                <dbl>
 1 380362. 599038.                              NaN    
 2 380388. 599038.                              NaN    
 3 380412. 599038.                              NaN    
 4 380438. 599038.                              NaN    
 5 380462. 599038.                              NaN    
 6 380488. 599038.                              NaN    
 7 380512. 599038.                              NaN    
 8 380538. 599038.                                0    
 9 380562. 599038.                                0.241
10 380588. 599038.                                2.22 
# ... with 65 more rows
```

Are these NA's resulting as there are no points in the pixels? I can't find any documentation stating that no points returns NA for pixel metrics, only for voxel_metrics. Thanks.

**Comment by Jean-Romain** [comment]
Without a reproducible example I'd say yes. A raster covers a rectangular region. If you have no point in one pixel the pixel must exist anyway so it is filled with `NA`. But here you have `NaN` which is surprising. Can't say more without a reproducible example.
