### ISSUE TITLE
Watershed

### ISSUE THREAD

**Issue by felipenorconsult** [r-lidar/lidR#662]
Hi,
 
I've been using your R package for tree segmentation quite some time, but suddenly it wouldn’t work for any reason:
 
> algo <- watershed(chm_s, th_tree = 4)
Error in watershed(chm_s, th_tree = 4) : unused argument (th = 4)

**Comment by Jean-Romain** [comment]
Weird. I don't think it comes from lidR. Do you have another package loaded that provides a function named `watershed`? What if you write `lidR::watershed(chm_s, th_tree = 4)`

**Comment by felipenorconsult** [comment]
Hi JR

Thanks a lot, that did the trick. 😊

Felipe Verdú
Teknikledare GIS och fjärranalys
Dir: +46 10 14 17 591 | Mob: +46 723 89 24 53
***@***.***
***@***.***
Norconsult AB
Box 8774, 402 76 Göteborg
Theres Svenssons gata 11, 417 55 Göteborg
Tel: +46 10 141 80 00
www.norconsult.se<http://www.norconsult.se/>
Every day we improve everyday life
