### ISSUE TITLE
terra interface

### ISSUE THREAD

**Issue by rhijmans** [r-lidar/lidR#667]
`lidR::raster_bbox`  uses

```r
bbox <- terra::ext(raster)
bbox <- bbox@ptr$vector
names(bbox) <- c("xmin", "xmax", "ymin", "ymax")
 ``` 

That breaks with the development version of terra. The @ptr$ methods are not really safe for use in other packages. Can you use the "official" interface instead? In this case 

```r
bbox <- terra::ext(raster)
bbox <- terra::as.vector(bbox)
``` 

Thanks!

**Comment by Jean-Romain** [comment]
`sf::st_bbox()` seems to works properly on `SpatRaster` so I'm now using `st_bbox()`. Thanks.
