### ISSUE TITLE
Problems in exporting LAS file after intensity normalization.

### ISSUE THREAD

**Issue by rorai-neto** [r-lidar/lidR#685]
I am performing intensities normalization in my LiDAR data.
On the first attempt to perform the `track_sensor`, an error message appears

> "Error: After keeping only first and last returns of multiple pulses returns, 16 pulses still have more than 2 points. This dataset is corrupted and gpstime is likely to be invalid.
In addition: Warning message:
There were 12 duplicated points. They were removed for processing. "

So I fixed it using the following:

```r
sectorder(las@data, gpstime, UserData, Z)
las@data[, `:=`(ReturnNumber = 1:.N, NumberOfReturns = .N), by = .(gpstime, UserData)]
las = las_update(las)
```
Afterwards, I can run the `track_sensor`, calculate the range and normalize the intensities.

However, when i try to export the point cloud after the normalization, the following error message appears:

> "Error: Invalid data: ReturnNumber is not an unsigned integer on 3 bits"

What does this message mean, and is it possible to fix this error?

Thanks in advance for the help.
All the best.

**Comment by Jean-Romain** [comment]
In 

```r
las@data[, `:=`(ReturnNumber = 1:.N, NumberOfReturns = .N), by = .(gpstime, UserData)]
```

You have one or several groups with more than 7 points. Thus you are assigning a return number > 7 which is not possible in a LAS file. I can say more without a reproductible example.

**Comment by rorai-neto** [comment]
> In
> 
> ```r
> las@data[, `:=`(ReturnNumber = 1:.N, NumberOfReturns = .N), by = .(gpstime, UserData)]
> ```
> 
> You have one or several groups with more than 7 points. Thus you are assigning a return number > 7 which is not possible in a LAS file version < 1.4. I can't say more without a reproductible example. The dataset was originally invalid, renumbering the point was unlikely to fix the problem. You must identify your problem first.

Thank you very much for your reply.
I used the las_check and I have the follow message

 Checking the data
  - Checking coordinates... ✓
  - Checking coordinates type... ✓
  - Checking coordinates range... ✓
  - Checking coordinates quantization... ✓
  - Checking attributes type... ✓
  - Checking ReturnNumber validity... ✓
  - Checking NumberOfReturns validity... ✓
  - Checking ReturnNumber vs. NumberOfReturns... ✓
  - Checking RGB validity... ✓
  - Checking absence of NAs...
    ✗ The following attributes contain NAs: Deviation
  - Checking duplicated points...
    ⚠ 51 points are duplicated and share XYZ coordinates with other points
  - Checking degenerated ground points... skipped
  - Checking attribute population...
    🛈 'ScanDirectionFlag' attribute is not populated
  - Checking gpstime incoherances
    ✗ 2182 pulses (points with the same gpstime) have points with identical ReturnNumber
  - Checking flag attributes... ✓
  - Checking user data attribute... ✓
 Checking the header
  - Checking header completeness... ✓
  - Checking scale factor validity... ✓
  - Checking point data format ID validity... ✓
  - Checking extra bytes attributes validity... ✓
  - Checking the bounding box validity... ✓
  - Checking coordinate reference system... ✓
 Checking header vs data adequacy
  - Checking attributes vs. point format... ✓
  - Checking header bbox vs. actual content... ✓
  - Checking header number of points vs. actual content... ✓
  - Checking header return number vs. actual content... ✓
 Checking coordinate reference system...
  - Checking if the CRS was understood by R...
    ✗ EPSG code 32767 unknown
 Checking preprocessing already done 
  - Checking ground classification... no
  - Checking normalization... no
  - Checking negative outliers... ✓
  - Checking flightline classification... yes
 Checking compression
  - Checking attribute compression...
   -  ScanDirectionFlag is compressed
   -  Classification is compressed
   -  Synthetic_flag is compressed
   -  Keypoint_flag is compressed
   -  Withheld_flag is compressed
   -  UserData is compressed
   -  PointSourceID is compressed

If it helps, attached is the link to download the point cloud tile.
https://www.dropbox.com/sh/0dtvj0iice4i7h2/AABJSs1YT--zH2ccaLQ7gtIYa?dl=0

Thank you very much.

**Comment by Jean-Romain** [comment]
I see

> ✗ 2182 pulses (points with the same gpstime) have points with identical ReturnNumber

However it does not use `UserData` for multibeam laser. So you may have less than this number if your sampling device is multibeam

**Comment by rorai-neto** [comment]
> I see
> 
> > ✗ 2182 pulses (points with the same gpstime) have points with identical ReturnNumber
> 
> However it does not use `UserData` for multibeam laser. So you may have less than this number if your sampling device is multibeam

I see.
Thank you very much.
Do you know how can i fix this to proceed with the intensities normalization?
All the best.
