### ISSUE TITLE
NumberOfReturns only support 3 bits

### ISSUE THREAD

**Issue by bbrede** [r-lidar/lidR#686]
I have a problem creating LAS objects with more than 8 returns. LAS v1.4 should support up to 15 returns, but this code:
`data <- data.frame(X = runif(100, 0, 100), Y = runif(100, 0, 100), Z = runif(100, 0, 20), NumberOfReturns = rep(15L, 100))
LAS(data)`
returns:
`Error: Invalid data: NumberOfReturns is not an unsigned integer on 3 bits`

**Comment by bbrede** [comment]
I realised LAS() produces by default v1.2 las specification format. Is there a way to choose v1.4?

**Comment by Jean-Romain** [comment]
For referencement: https://gis.stackexchange.com/questions/461921/create-las-v1-4-from-scratch
