### ISSUE TITLE
having an issue in "normalized_height"

### ISSUE THREAD

**Issue by taeyoonlee87** [r-lidar/lidR#687]
I used the "nomalized_height" command and encountered the same error when it was running using a high-performance computing system (HPC). 

In the previous works, this code worked without any issue though when it was running in my desktop and a high-performance computing system.

However, whenever I run it using HPC it gave me same error. 

The error was indicated like 

> opt_output_files(las_cat) <-"/scratch/tl96575/tin_0628/dtm/norm_{XLEFT}_{YBOTTOM}"
> lasnorm <- normalize_height(las_cat, DTM)
Chunk 14 of 635 (0.2%): state ✗
An error occurred when processing the chunk 14. Try to load this chunk with:
 chunk <- readRDS("/tmp/RtmpJhamdq/chunk14.rds")
 las <- readLAS(chunk)
i is invalid type (matrix). Perhaps in future a 2 column matrix could return a list of elements of DT (in the spirit of A[B] in FAQ 2.14). Please report to data.table issue tracker if you'd like this, or add your comments to FR #657.
Error in any_list[[1]] : subscript out of bounds
Calls: normalize_height ... normalize_height.LAScatalog -> catalog_map -> catalog_apply -> engine_merge
In addition: Warning messages:
1: There are 3755 points flagged 'withheld'.
2: In raster_cell_from_xy(raster, x, y) :
  NAs introduced by coercion to integer range
Execution halted

Do you have ever seen this error?

**Comment by Jean-Romain** [comment]
Not at all. I need a reproducible exemple.
