### ISSUE TITLE
Read .copc.laz files

### ISSUE THREAD

**Issue by ouroukhai** [r-lidar/lidR#692]
Hello,
is there a way to read .copc.laz files directly from lidR? The only solution I've found so far is to convert to .laz via PDAL library.
Thank you for the time

**Comment by wiesehahn** [comment]
That sounds great, does this also allow a more performant plotting experience? E.g. take advantage of the internal octree tiling to render only points in sight.

**Comment by Jean-Romain** [comment]
> take advantage of the internal octree tiling to render only points in sight.

No. But I will probably work on it later. I have some existing code that may be used for that. Yet doing that with `rgl` is not straightforward at all.

**Comment by Jean-Romain** [comment]
The github version of rlas has COPC support. https://github.com/r-lidar/rlas. On CRAN soon.
