### ISSUE TITLE
las-files without Points

### ISSUE THREAD

**Issue by PiusHauenstein** [r-lidar/lidR#711]
if las_check should analyze an empty las-file, it crashes:

```r
ctg <- readLAScatalog("D:\\LiDAR2019\\laz_Filter_GP_Cleaned")
las_check(ctg, deep = TRUE)
#> An error occurred when processing the chunk 8. Try to load this chunk with:
#>  chunk <- readRDS("C:\Users\phca\AppData\Local\Temp\2\Rtmp6BsQIE/chunk8.rds")
#>  las <- readLAS(chunk)
#> [ext] invalid extent
#> Error in names(out) <- basename(las@data[["filename"]]) : 
#>   'names' attribute [1614] must be the same length as the vector [7]
#> In addition: There were 36 warnings (use warnings() to see them)
```

Empty las-files can happen, if you process a chunk of files previously for example with lastools with a filter condition

**Comment by Jean-Romain** [comment]
Please share a empty file. I cannot produce an empty file with las2las. It does not write empty files. I don't know how you produced an empty file. Thanks

**Comment by PiusHauenstein** [comment]
You can produce one with "lasduplicate -keep_class xx", xx must be a not existing class in the input file

**Comment by Jean-Romain** [comment]
I do not have a license of lastools. Please share a file..

**Comment by PiusHauenstein** [comment]
[empty.zip](https://github.com/r-lidar/lidR/files/12618157/empty.zip)

**Comment by Jean-Romain** [comment]
Ok the problem is less serious than expected. I though that it crashed when reading 0 point but it only produced a regular errors and stop.


```r
f = "/home/jr/Téléchargements/lidR issues/issue 711/empty.las"
las = lidR::readLAS(f)
lidR::las_check(las)
```

**Comment by Jean-Romain** [comment]
You can get rid of empty files to fix you problem upstream. This is what I will implement as a first layer of protection. I will also exit `las_check()` early for 0 point LAS objects

```r
ctg = ctg[ctg$Number.of.point.records > 0,]
```
