### ISSUE TITLE
Individual tree segmentation -> dalponte2016

### ISSUE THREAD

**Issue by utzdrechsler** [r-lidar/lidR#713]
This is the code from the lidrBook that I have used.

```r
algo <- dalponte2016(chm_p2r_05_smoothed, ttops_chm_p2r_05_smoothed)
algo <- segment_trees(las, algo) # segment point cloud
plot(algo, bg = "white", size = 4, color = "treeID") # visualize trees
```

The derived chm and ttop segmentation are from the chapter before and both work.
When I try to run dalponte2016 I get the followin error message:
Error in loadNamespace(x) : there is no package ‘future’

Anybody else got the same issue and knows what to do?

**Comment by utzdrechsler** [comment]
Sorry it was very simple:

install.packages("future")
library(future)

**Comment by Jean-Romain** [comment]
Simple to solve yet there is a bug. It should work without future.

**Comment by Jean-Romain** [comment]
Fixed
