### ISSUE TITLE
rasterize_terrain() only outputs the last tile of LAScatalog

### ISSUE THREAD

**Issue by natedailey7** [r-lidar/lidR#729]
When I use `rasterize_terrain()` to create a DTM based on a LAScatalog, only the last tile is shown in my output. The same happens when I use `normalize_height()`. This is a continuation of a GIS Stack Exchange post [here](https://gis.stackexchange.com/questions/470222/normalizing-lascatalog-only-outputs-one-tile). 

I uploaded my data (2 las files) along with my script to Google Drive [here](https://drive.google.com/file/d/1fezB3Fc0MVcnvO5KJJervxQHL41sNzhb/view?usp=sharing).

```
install.packages("lidR")
library(lidR)

WORKING_DIRECTORY <- "path"
setwd(WORKING_DIRECTORY)

# Assign relative paths for las files and R Outputs. 
LAS_CATALOG <- "data"
R_OUTPUT_FILES <- "R_Outputs"

# read the two las files
ctg <- readLAScatalog(LAS_CATALOG)

plot(ctg)
```
![image](https://github.com/r-lidar/lidR/assets/72231724/584ba1b4-e3c2-4d84-9ff0-67c32e8ef402)

```
# Assign location for output files and allow overwriting. 
opt_output_files(ctg) <- R_OUTPUT_FILES
ctg@output_options$drivers$SpatRaster$param$overwrite <- TRUE

# create dtm. For me, only the last tile is shown in the plot. 
dtm <- rasterize_terrain(ctg, algorithm=knnidw(), overwrite=TRUE)
plot(dtm)
```
![image](https://github.com/r-lidar/lidR/assets/72231724/a1e47f7c-780f-4bc1-9323-50f34a3fa586)
```
# Normalize height -- again, only the last tile is processed for me. 
norm <- normalize_height(ctg, tin())
plot(norm)
```

![image](https://github.com/r-lidar/lidR/assets/72231724/5b39bb66-c73d-4f4a-8dc9-1ce50ca7fdbc)

Let me know if you have any ideas or suggestions -- thank you.

**Comment by Jean-Romain** [comment]
```r
R_OUTPUT_FILES <- "R_Outputs"
opt_output_files(ctg) <- R_OUTPUT_FILES
```

Your path is not templated. So it processes the first LAS file, writes it in `R_ouput.tif` then the second LAS file also in `R_output.tif` and erases the first raster. Use the name of the LAS files to name your rasters

```r
R_OUTPUT_FILES <- "{ORIGINALFILENAME}_chm"
opt_output_files(ctg) <- R_OUTPUT_FILES
```

I could have answered on stack exchange if you provided a reproducible code :wink: :

**Comment by natedailey7** [comment]
AMAZING!! Worked perfectly -- Thank you so much 😄
