### ISSUE TITLE
Can readLASCatalog access s3:// locations for files?

### ISSUE THREAD

**Issue by omshinde** [r-lidar/lidR#756]
Hi team.

I am working on a task which requires reading assets stored in a STAC using `rstac` in a vector. This vector comprises of AWS S3 `s3://` links. I have to pass this vector with all the `s3` links to `readLASCatalog` for compelting my task.

Is it possible? Can `readLASCatalog` take a vector with `s3` links as input? Otherwise I'll have to download the files locally and pass it to the `readLASCatalog` function.

Thank you for the great work.

**Comment by Jean-Romain** [comment]
You must have the data stored locally. Remote data won't be read through the network. The best that could be done would be to download on the fly the data transparently but this feature is not implemented in lidR.
