### ISSUE TITLE
Large area point cloud disappears when plotting with color="Z" and legend=TRUE

### ISSUE THREAD

**Issue by 1iny** [r-lidar/lidR#764]
Hi,

I've encountered an issue when plotting large area point clouds using lidR. The point cloud disappears when I set color = "Z" and legend = TRUE for areas around 100 hectares in size, if I set legend = FALSE, then no issue. This issue only occurs with relatively large area point clouds (even with low point density). I tried in different PCs and the same issue still exist.

Environment:
- R version: 4.3.3
- lidR version: 4.1.2
- Operating System: Windows 10
- RAM: 128GB

Code Example:
plot(large_cloud_las, color = "Z", legend = TRUE)

![Issue](https://github.com/r-lidar/lidR/assets/24280645/cd2f3f17-9415-44d7-839f-04e300a307ad)

**Comment by Jean-Romain** [comment]
How many points is large enough to reproduce?

**Comment by 1iny** [comment]
> How many points is large enough to reproduce?

My las file is about 200 points/sqm, area is 76 ha. I suspect its due to the area is too large. Cheers

**Comment by Jean-Romain** [comment]
76 ha is 0.76 km² so 3/4 of the standard 1km² file. However you have approx 150 million points. `rgl` definitively can't handle that.
