### ISSUE TITLE
Clarification about resolution units for sample_maxima (highest and lowest)

### ISSUE THREAD

**Issue by mcgregorian1** [r-lidar/lidR#765]
Hi, I've been trying to determine what the resolution of the `highest()` and `lowest()` grids for use within `decimate_points()` means in real-world terms - is it in meters? I.e., for `highest()` the default is 1m resolution grid and the highest point within each 1m x 1m grid cell are kept?

If this is correct, can this language please be added to the documentation? I've searched through the CRAN pdf as well as the vignettes, but there is no wording explicitly saying that the `res` argument is in meters. Or if this is described elsewhere, can you please point me to that?

Thanks!

**Comment by Jean-Romain** [comment]
the resolution and all other value with units are in the units of the point cloud. It keeps the highest point for each 1x1 cell of the grid. `1` being likely one meter or sometime one foot.
