### ISSUE TITLE
Error: no applicable method for 'readLAS' applied to an object of class "LAS"

### ISSUE THREAD

**Issue by leonard-leo** [r-lidar/lidR#777]
Hello,

I got the error below after running this code chunk:

> sample <- lidR::readLAS(file.path("sample.las")
> voxels_lad <- leafR::lad.voxels(sample, grain.size = 2, k = 1)

> Error in UseMethod("readLAS", files) : 
  no applicable method for 'readLAS' applied to an object of class "LAS"

The sample.las file is properly loaded using the readLAS function, so I honestly have no idea why I'm getting that error.... 
Any ideas? I'm using a Macbook Pro M1, R version 4.4.1, and latest versions of the lidR and leafR packages.

Thank you!
Leonardos

**Comment by Jean-Romain** [comment]
This is an error with the `leafR` package. I'm not the author of `leafR`. My guess is that `las.voxels` is expecting the path to the file and loads it on the fly with `readLAS()` internally.
