### ISSUE TITLE
Overwrite repeated computations

### ISSUE THREAD

**Issue by Cidree** [r-lidar/lidR#780]
Hello! 
I ran wrong my `pixel_metrics()` one time, and then I wanted to create them again without changing the output files. However, when I try to run twice the same code I receive the error:

![image](https://github.com/user-attachments/assets/634f83d7-f22e-40f0-8834-d141fd90b4ae)

I tried to add `writeRaster = TRUE`, but as I understand it, it's not implemented and I should use new file names and recreate them.
Is there any other way to overwrite the items?

**Comment by Jean-Romain** [comment]
See https://gis.stackexchange.com/questions/463618/overwriting-files-in-function-pixel-metrics/463629#463629
